### ISSUE TITLE
T8A3 feedback

### ISSUE THREAD

**Issue by nirandiw** [CS2103AUG2016-T09-C2/main#62]
### User stories
- "search for a particular task" use case - what is the command for this in the user guide command summary?
- "view all complete/incomplete tasks" use cases - what is the command for this in the user guide command summary?
- Take note that once i do  "find XXX" in your system right now I have no way to go back to the default view. Looks like a major design flaw right? Hint: a command to list all tasks 
- User stories are good but there are inconsistencies with main user stories and the commands given in the user guide. 
### User cases
- Checked only few use cases. Looks good and comprehensive. 👍 
### NFR
- "Should ensure reminders for overlapping tasks do not overwrite each other" Sounds like a functional requirement to me.
- Being able to save is a must have feature as per the handbook isn't it?
- Should recover from major errors efficiently. Sounds really vague
- the module handbook has a lot of project constraints. May be you can add a hyperlink to that. 
### Product Survey
- You guys have the capability survey more products.

**Comment by weiyin17** [comment]
Updated commands in UserGuide to suit User Stories.
Updated NFRs.
Added more product surveys.
